#!/bin/sh

rm -rf *.txt *.s
./mycoolc -g -t $* -o 1.s  
cd ~/dragon/assignment4 
./mycoolc -g -t  $* -o 2.s
mv 2.s ~/143/assignment4
cd ~/143/assignment4
diff 1.s 2.s > 3.txt 
cat 3.txt
vi -d 1.s 2.s
